---
- name: install apache on remote server
  hosts: web
  become: yes
  tasks:


    - name: upadees packages 
      apt: 
        update_cache: yes

    - name: install apache2
      apt:
       name: apache2
       state: present

    - name: ensure that apache2
      service:
        name: apache2
        state: started
        enabled: yes
        